### ISSUE TITLE
A mana system / Spell recourse system

### ISSUE THREAD

**Issue by Jokies77** [flashgnash/ordis#4]
Due to the change to a more complex system of using magic in game, tracking spell casting resource/mana is now more prevalent, because of this it would be useful to have commands to automatically track this rather than having to manually update it each time. Allocating costs to certain spells and abilities would mean players would need to spend far less time calculating spell costs streamlining the game as a whole.

**Comment by flashgnash** [comment]
The commands I'm thinking are:

/list_spells (lists spells from character sheet message)
/cast_spell (subtracts spell from mana)

/mod_mana (modify mana, first argument will be for example +50, -50 etc)

/mana (prints out current mana)

/reset_mana (resets mana to maximum)

It may also be a good idea to update mana on the player's character sheet, though the bot can't edit other people's messages so it will need to be in its own message managed by ordis

**Comment by flashgnash** [comment]
Fixed as of merge of #24
